name: Run Unit Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
          architecture: x64