name: Run Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
          architecture: x64

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
