name: Run Unit Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Initialize Gradle Wrapper
        run: gradle wrapper

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          architecture: x64

      - name: Build with Gradle
        run: gradlew build

      - name: Run tests
        run: gradlew test
